### ISSUE TITLE
binocle/test/TestGps.java is 404 here on github

### ISSUE THREAD

**Issue by supaplextor** [Genymobile/genymotion-binocle#5]
https://github.com/Genymobile/genymotion-binocle
https://github.com/Genymobile/genymotion-binocle/blob/master/binocle/src/instrumentTest/java/com/genymotion/binocle/test/TestGps.java

**Comment by eyal-lezmy** [comment]
Hi,

Where did you find this link? 
The good one is now this: https://github.com/Genymobile/genymotion-binocle/blob/master/binocle/src/androidTest/java/com/genymotion/binocle/test/TestGps.java

**Comment by supaplextor** [comment]
I think it's probably from the README.md (I'm green to markdown).  Search for TestGps.java on this page: https://github.com/Genymobile/genymotion-binocle

**Comment by eyal-lezmy** [comment]
@supaplextor thanks a lot for highlighting this. All the links have been fixed on the doc.
I close the issue as the problem is now solved.

Cheers
Eyal
